import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { iTombstone, iProgramTombstone } from '../models/tombstone.class';
import { iPerson } from '../models/person.class';


@Injectable({
  providedIn: 'root'
})
export class TombstoneService {
  // ['program_applicationlication', 'budget_proposal', 'status_report', 'expense_report']

  getTombstones(bceid: string): Observable<iTombstone[]> {
    const t = [
      {
        formName: 'Status Report (Sched X)',
        formType: 'status_report',
        formDeadline: new Date('2019-06-30'),
        formStatus: 'Action Required',
        forDateRangeStart: new Date('2019-06-02'),
        forDateRangeEnd: new Date('2019-06-30'),
        note: '',
        contractNumber: '1097583',
        organizationId: 'aacb8575ac5acb363a64ca',
        programId: 'NCC-1701',
        frequency: 'monthly',
      } as iTombstone,
      {
        formName: 'Status Report (Sched X)',
        formType: 'status_report',
        formDeadline: new Date('2019-07-30'),
        formStatus: 'Action Required',
        forDateRangeStart: new Date('2019-07-02'),
        forDateRangeEnd: new Date('2019-07-30'),
        note: '',
        contractNumber: '1097583',
        organizationId: 'aacb8575ac5acb363a64ca',
        programId: 'NCC-1701',
        frequency: 'monthly',
      } as iTombstone,
      {
        formName: 'Status Report (Sched X)',
        formType: 'status_report',
        formDeadline: new Date('2019-08-30'),
        formStatus: 'Action Required',
        forDateRangeStart: new Date('2019-08-02'),
        forDateRangeEnd: new Date('2019-08-30'),
        note: '',
        contractNumber: '1097583',
        organizationId: 'aacb8575ac5acb363a64ca',
        programId: 'NCC-1701',
        frequency: 'monthly',
      } as iTombstone,
      {
        formName: 'Status Report (Sched X)',
        formType: 'status_report',
        formDeadline: new Date('2019-09-30'),
        formStatus: 'Action Required',
        forDateRangeStart: new Date('2019-09-02'),
        forDateRangeEnd: new Date('2019-09-30'),
        note: '',
        contractNumber: '1097583',
        organizationId: 'aacb8575ac5acb363a64ca',
        programId: 'NCC-1701',
        frequency: 'monthly',
      } as iTombstone,
      {
        formName: 'Program Application (Sched G)',
        formType: 'program_application',
        formDeadline: new Date('2019-12-31'),
        formStatus: 'Action Required',
        forDateRangeStart: new Date('2019-01-02'),
        forDateRangeEnd: new Date('2019-12-31'),
        note: 'Please submit your annual Program Application (Sched G) by the Due Date',
        contractNumber: '1097583',
        organizationId: 'aacb8575ac5acb363a64ca',
        programId: 'NCC-1701',
        frequency: 'annual',
      } as iTombstone,
      {
        formName: 'Budget Proposal (Sched F)',
        formType: 'budget_proposal',
        formDeadline: new Date('2019-01-02'),
        formStatus: 'Started',
        forDateRangeStart: new Date('2019-01-02'),
        forDateRangeEnd: new Date('2019-12-31'),
        note: '',
        contractNumber: '1097583',
        organizationId: 'aacb8575ac5acb363a64ca',
        programId: 'wert',
        frequency: 'quarterly',
      } as iTombstone,
      {
        formName: 'Expense Report (Sched F)',
        formType: 'expense_report',
        formDeadline: new Date('2019-12-31'),
        formStatus: 'Submitted',
        forDateRangeStart: new Date('2019-01-02'),
        forDateRangeEnd: new Date('2019-12-31'),
        note: '',
        contractNumber: '1097583',
        organizationId: 'aacb8575ac5acb363a64ca',
        programId: 'erty',
        frequency: 'quarterly',
      } as iTombstone,
      {
        formName: 'Program Application (Sched G)',
        formType: 'program_application',
        formDeadline: new Date('2019-12-31'),
        formStatus: 'Late',
        forDateRangeStart: new Date('2019-01-02'),
        forDateRangeEnd: new Date('2019-12-31'),
        note: '',
        contractNumber: '1097583',
        organizationId: 'aacb8575ac5acb363a64ca',
        programId: 'rtyu',
        frequency: 'annual',
      } as iTombstone,
      {
        formName: 'Program Application (Sched G)',
        formType: 'program_application',
        formDeadline: new Date('2019-12-31'),
        formStatus: 'Missed',
        forDateRangeStart: new Date('2019-01-02'),
        forDateRangeEnd: new Date('2019-12-31'),
        note: '',
        contractNumber: '1097583',
        organizationId: 'aacb8575ac5acb363a64ca',
        programId: 'uiop',
        frequency: 'annual',
      } as iTombstone,
      {
        formName: 'Program Application (Sched G)',
        formType: 'program_application',
        formDeadline: new Date('2019-12-31'),
        formStatus: 'Missed',
        forDateRangeStart: new Date('2019-01-02'),
        forDateRangeEnd: new Date('2019-12-31'),
        note: '',
        contractNumber: '1097583',
        organizationId: 'aacb8575ac5acb363a64ca',
        programId: 'asdf',
        frequency: 'annual',
      } as iTombstone,
      {
        formName: 'Program Application (Sched G)',
        formType: 'program_application',
        formDeadline: new Date('2019-12-31'),
        formStatus: 'Complete',
        forDateRangeStart: new Date('2019-01-02'),
        forDateRangeEnd: new Date('2019-12-31'),
        lastUpdated: new Date('2019-12-12'),
        note: '',
        contractNumber: '1097583',
        organizationId: 'aacb8575ac5acb363a64ca',
        programId: 'sdfg',
        frequency: 'annual',
        internalNote: '',
      } as iTombstone,
      {
        formName: 'Program Application (Sched G)',
        formType: 'program_application',
        formDeadline: new Date('2019-12-31'),
        formStatus: 'Complete',
        forDateRangeStart: new Date('2019-01-02'),
        forDateRangeEnd: new Date('2019-12-31'),
        lastUpdated: new Date('2019-12-12'),
        note: '',
        contractNumber: '1097583',
        organizationId: 'aacb8575ac5acb363a64ca',
        programId: 'dfgh',
        frequency: 'annual',
        internalNote: '',
      } as iTombstone,
    ];
    return of(t);
  }
  getProgramTombstones(bceid: string): Observable<iProgramTombstone[]> {
    const t: iProgramTombstone[] = [{
      programContact: {
        firstName: 'Tony',
        middleName: 'Eugene',
        lastName: 'Stark',
        title: 'Man of Iron',
        email: 'tonystark67@hotmail.com',
      } as iPerson,
      programName: 'Marvel Compassion Club',
      contractNumber: 'PDA-12345',
      organizationId: 'BCEID goes here',
      programId: 'NCC-1701'
    },
    {
      programContact: {
        firstName: 'Dick',
        middleName: 'Pete',
        lastName: 'Grayson',
        title: 'The Robin',
        email: 'trickydickgrayson@yahoo.com.cn',
      } as iPerson,
      programName: 'Social Work Metropolis',
      programId: 'wert',
      contractNumber: 'PDF-91191',
      organizationId: 'BCEID goes here',
    }] as iProgramTombstone[];
    return of(t);
  }
}
