version: "3.6"
services:
  vsd-public-app-frontend:
    build: .
    image: vsd-public-app-frontend
    container_name: vsd-public-app-frontend
    command: "npm start -- --poll=500"
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - NODE_ENV=development
      - API_URL
      - SM_TOKEN
      - DEV_USER
      - DEV_BCSC_USER
